### ISSUE TITLE
Can't retrieve crafted items from saw bench (ATM9 Modified Modpack)

### ISSUE THREAD

**Issue by logixcraft** [roberttkahelin8/thingmajigs#7] opened 2023-09-12 05:23 UTC
Whenever I go to craft  a thingamajig the item I try to retrieve from the sawbench the crafted item vanishes.  I've been trying to track down which mods are causing it with no luck so far.

I'm running a modified version of AllTheMods 9

I don't know what you need so I'm including my modlist and level.dat

[Modlist.txt](https://github.com/roberttkahelin8/thingmajigs/files/12582594/Modlist.txt)
[level.zip](https://github.com/roberttkahelin8/thingmajigs/files/12582604/level.zip)

**Comment by roberttkahelin8** [comment] 2023-09-14 12:58
Could you perhaps send some screenshots of this issue? A modlist and a level file doesn't help very much. I cannot download every mod on this list without taking some time. Could you perhaps tell me specifically what mods you added to the default modlist of ATM9? And what modpack version of ATM9 are you using?

**Comment by roberttkahelin8** [comment] 2023-09-14 13:32
@logixcraft Corail sawmill is for cutting wood items only. It will not do stonecutter recipes. If this is the sawmill block you are talking about this is not a bug, rather an intended feature by the mod developer.

**Comment by logixcraft** [comment] 2023-09-14 19:14
https://i.imgur.com/Ek1mtnv.mp4  Video of the issue.  I know it was working fine earlier on, but some changes were made and I'm not sure what caused the conflict, I'm slowly slowly disabling and testing different mods to track down the issue.

**Comment by roberttkahelin8** [comment] 2023-09-14 22:20
Based on the video, it appears this is a handheld crafting item. Due to personal experience with item desync, I think perhaps the amount of recipes (stonecutter) being loaded in on this screen for this item might be a cause for concern. If you track down the mod that adds this item, try looking for a bug report on it. If there is a known bug with this mod regarding this item, it may be a universal issue.

**Comment by roberttkahelin8** [comment] 2023-09-14 22:25
In my experience with my mod, the vanilla stonecutter never has desync issues when switching and crafting at a standard speed (one click every 2->~3 seconds).

**Comment by roberttkahelin8** [comment] 2023-09-14 22:28
A lot of mods with custom crafting interfaces seem to have issues similar to this (as far as i can tell) because they aren't direct access points to a block entity but rather an interface to the inventory of the player and a 'fake' crafting entity.

**Comment by roberttkahelin8** [comment] 2023-11-20 01:28
Issue may persist if multiple stonecutter recipes using same item are loaded at once. In survival, Thingamajigs 1.6.7+ fixes this issue as no items are breaking the stonecutter anymore, because of the addition of Components. Closing this as complete now.

**Closed by roberttkahelin8** 2023-11-20 01:28 UTC
Labels: bug, needs more testing
